#   Version 9.4.4
[thruput]
maxKBps = 256

[metrics]
interval = 60
# 60 seconds metrics logging interval
[tcpin_connections]
interval = 60
[thruput:thruput]
interval = 60
[thruput:index_thruput]
interval = 60
[queue]
interval = 60
[dutycycle]
interval = 60
[search_concurrency]
interval = 60
[searchscheduler]
interval = 60
[executor]
interval = 60
[jobs]
interval = 60
[search_pool]
interval = 60
[smartbus]
interval = 60
